# Generated by Django 3.1 on 2020-08-23 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manageapp', '0003_milkentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkentry',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='milkentry',
            name='milktype',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='milkentry',
            name='bill',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='milkentry',
            name='fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='milkentry',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='milkentry',
            name='snf',
            field=models.FloatField(default=0.0),
        ),
    ]
