# Generated by Django 3.1 on 2020-09-14 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manageapp', '0004_auto_20200823_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkentry',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
    ]
